name: Sync workshop.ipynb to instructor_scverse-ml-workshop-2024 in the scverse-ml-workshop-2024 TileDB-Cloud namespace
on:
  push:
    branches:
    - main
    paths:
    - 'workshop.ipynb'
  workflow_dispatch:
    inputs:
      dst_name:
        description: 'Name to put the workshop.ipynb at'
        required: true
        default: 'instructor_scverse-ml-workshop-2024'
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -e .
    - run: scverse nb put workshop.ipynb ${{ inputs.dst_name || 'instructor_scverse-ml-workshop-2024' }}
      env:
        TILEDB_REST_TOKEN: ${{ secrets.TILEDB_REST_TOKEN }}
